// Programmer: Jack Sutton
// Team Member: John Burke
// Bolt ID: SB E2F0
// Date: 4.30.2024
// Program: Maze Competition
// Program URL: https://edu.sphero.com/program/16788346/edit


async function startProgram() {
	// Programmer: John Burke - Start Text & Audio Checkpoint Commit - Date:




	// Programmer:             - Blue LED Checkpoint Commit - Date:




	// Programmer:             - Sound one Checkpoint Commit - Date:




	// Programmer:             - RED LED Checkpoint Commit - Date:




	// Programmer:             - Sound Two Checkpoint Commit - Date:




	// Programmer:             - Green LED Checkpoint Commit - Date:




	// Programmer:             - Purple LED & Sound Three Checkpoint Commit - Date:




	// Programmer:             - Finish Text & Audio Checkpoint Commit - Date:
}
